#!/usr/bin/env bash
# Execute a command in the container
set -ue
thisdir="$(dirname "${BASH_SOURCE[0]}")"
source "${thisdir}/functions-r.sh"


CONTAINER="$thisdir/r-py.sif"
BIND_PROJECT_TO="/proj"    # Where project directory is mounted inside of the container

# Accept unset as empty, because it is an array and for arrays,
# A=() means A is unset
: "${EXTERNAL_FILES-}"     # Which external files/folders are accessible. 

# === Helpful messages for first-time users ==================

if [ -z "${PROJECT_DIR-}" ]; then
  echo "ERROR: Don't know project directory." >&2
  echo "Execute 'createproject' if you run RStudio in this directory for the first time" >&2
  exit 1
fi
# ===== Default settings for Singularity =====================

# ...to singularity instance
ARGS_INSTANCE=(
  --contain
  -H "$PROJECT_DIR:$BIND_PROJECT_TO"
)

# ... to singularity exec
# (if no instance is started, then $ARGS_INSTANCE is
# also provided to singularity exec)
ARGS_EXEC=(
  --cleanenv
)

# Add external files as "-B...." arguments to singularity
# command line
for i in ${!EXTERNAL_FILES[@]}; do
  echo "DIR: ${EXTERNAL_FILES[$i]}"
  ARGS_INSTANCE+=(-B "${EXTERNAL_FILES[$i]}")
done


# ===== Forward to starting script ==========================

if [ "$#" = 0 ]; then
  echo "Argument required (try --help)" >&2
  exit 1
fi


cexec "$@"
