#!/bin/bash
set -ue

# Path to the SIF file that is the container
CONTAINER="$CONTAINER_DIR/rstudio.sif"

# Path (host system) where the session data of different RStudio Server
# sessions is stored.  Per session, a subfolder is created that is mounted to
# ~/.rstudio inside the container.  Also, the .pid files are created here,
# holding information about network port, host machine and more.
DIR_RUN=".run"

# Further arguments to forward to "singularity instance start ..."
ARGS_INSTANCE=()

# Further arguments to forward to "singularity exec ..."
ARGS_EXEC=()


# === Parse the user arguments ==================================
thisdir="$(dirname "${BASH_SOURCE[0]}")"

source "$thisdir/rstudio_adv"

