#!/usr/bin/env bash
set -ue
thisdir="$(realpath -s "$(dirname "${BASH_SOURCE[0]}")")"
#
# Start the RStudio Server container where this folder is set as the 
# project directory by executing this file.
# 
# Use --help to print the help text.
#
# === Settings ===========================================================

# Edit this section to change the container options of this project. They
# are communicated to the container as environment variables. See the
# beginning of the scripts "rstudio" and "rstudio_adv" to see which 
# environment variables are expected.

# PROJECT_DIR:
# Per default this is set to the directory where this script lies.
PROJECT_DIR="$thisdir"

# BIND_PROJECT_TO:
# On which path the current folder will be visible inside the container
BIND_PROJECT_TO="/proj"

# EXTERNAL_FILES:
# Files/directories that are available in the container besides the project
# directory.
# The follwing example makes the directory /home/user/datasets available
# inside the container as "/ext/input", read-only:
#
#   "/home/user/datasets/:/ext/input:ro"  (including quotes)
#
# The first path must exist. The second path can be freely chosen.
# Omit ":ro" to enable write access from within the container.
# Separate multiple entries by newlines.
#
EXTERNAL_FILES=(
# "/home/user/datasets/:/ext/input:ro" 
)

# On which address and on which port range to start RStudio
ADDRESS="127.0.0.1"
PORT_MIN="8000"
PORT_MAX="8200"


# CONTAINER_DIR:
# Where the RStudio Server container is located (directory).
###SED_REPLACE_HERE###


# ========= END OF SETTINGS ==================================================


# Further options can be set if the lines below are changed to not start the
# the script "rstudio" but "rstudio_adv". See the source of that script for
# info.
# Find container no matter of $PWD and whether CONTAINER_DIR is relative or absolute
CONTAINER_DIR="$(cd "$thisdir"; realpath -s "$CONTAINER_DIR")"
source "${CONTAINER_DIR}"/rstudio "$@"
